apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      tushar: final-project

  template:
    metadata:
      name: redis-cli
      labels:
        tushar: final-project

    spec:
      restartPolicy: Always
      containers:
      - name: redis-cli
        image: redis
        command: ['sh', '-c', 'sleep 100000']
